CREATE DATABASE Purbeurre;

USE Purbeurre;

CREATE TABLE Category(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (40) NOT NULL)
    ENGINE = InnoDB;

CREATE TABLE Product(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (150) NOT NULL,
    brand VARCHAR (100) NOT NULL,
    nutriscore CHAR(1) NOT NULL,
    store VARCHAR(150),
    cat_id INT UNSIGNED DEFAULT NULL,
    url VARCHAR (150) NOT NULL,
    CONSTRAINT fk_cat_id FOREIGN KEY (cat_id) REFERENCES Category(id) ON DELETE SET NULL)
    ENGINE = INNODB;

CREATE TABLE Favorite(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (150) NOT NULL,
    brand VARCHAR (100) NOT NULL,
    nutriscore CHAR(1) NOT NULL,
    store VARCHAR(150),
    cat_id INT UNSIGNED DEFAULT NULL,
    prod_id INT UNSIGNED DEFAULT NULL,
    url VARCHAR (150) NOT NULL,
    CONSTRAINT fk_fav_cat_id FOREIGN KEY (cat_id) REFERENCES Category(id) ON DELETE SET NULL,
    CONSTRAINT fk_prod_id FOREIGN KEY (prod_id) REFERENCES Product(id) ON DELETE SET NULL)
    ENGINE = INNODB;
