CREATE DATABASE IF NOT EXISTS Purbeurre;

USE Purbeurre;

CREATE TABLE IF NOT EXISTS Category(
    id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (40) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS Product(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR (150) NOT NULL,
    brand VARCHAR (100) NOT NULL,
    nutriscore CHAR(1) NOT NULL,
    store VARCHAR(150),
    cat_id INT UNSIGNED DEFAULT NULL,
    url VARCHAR (150) NOT NULL,
    favorite SMALLINT (1),
    CONSTRAINT fk_cat_id FOREIGN KEY (cat_id) REFERENCES Category(id) ON DELETE SET NULL);


